apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-ops
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"rabbitmq_host":"rabbitmq","rabbitmq_queue":"scraper","rails_app":"production","redis_channel_prefix":"scraper_ops_production","redis_db":"0","redis_host":"redis","redis_port":"6379","redis_url":"redis://redis:6379/1","scraper_ops_database_host":"postgres","scraper_ops_database_name":"scraper_ops_production","scraper_ops_database_port":"5432"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"scraper-ops","namespace":"se-test"}}  
data:
  rabbitmq_host: rabbitmq
  rabbitmq_queue: scraper
  rabbitmq_vhost: "/"
  rabbitmq_port: "5672"
  rails_app: production
  redis_channel_prefix: scraper_ops_production
  redis_db: "0"
  redis_host: redis
  redis_port: "6379"
  redis_url: redis://redis:6379/1
  scraper_ops_database_name: scraper_ops_production
  scraper_ops_database_host: postgres
  scraper_ops_database_port: "5432"


